{
 "title": "Meta Service Overview",
 "tags": [
  "services",
  "meta",
  "loki"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Meta Requests Per Minute",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"meta\"} | json | __error__=\"\" | path != \"/\" [1m]))",
     "legendFormat": "meta req/min"
    }
   ]
  },
  {
   "title": "Meta Error Requests (4xx/5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum(count_over_time({service=\"meta\"} | json | __error__=\"\" | path != \"/\" | status_code =~ \"4..|5..\" [1m]))",
     "legendFormat": "meta 4xx/5xx req/min"
    }
   ]
  },
  {
   "title": "Meta Logs",
   "type": "logs",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "{service=\"meta\"} | json | __error__=\"\" | path != \"/\""
    }
   ]
  }
 ]
}